sudo: required

language: ruby

services:
  - docker
addons:
  artifacts: true
   paths:
    - out
  apt:
   packages:
    # Dependencies from tutorial
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libncurses5-dev
    - libusb-1.0-0
    - libboost-dev
    - zip

# Environment
env:
 global:
  - VERILATOR_ROOT=$TRAVIS_BUILD_DIR/tools/verilator
  - RISCV=$TRAVIS_BUILD_DIR/riscv-tools-$BRANCH_N
  - PATH=$VERILATOR_ROOT/bin:$PATH:$RISCV/bin
  - JOBS=4

before_install:
 - git submodule update --init --recursive

# Execute the build
install:
 - git clone -b $BRANCH_N $REPO $BRANCH_N
 - cd $BRANCH_N
 - git submodule update --init
 - cd riscv-tools
 - time > $RISCV/test_log.txt
# - git submodule update --init --recursive
# - bash build.sh

#script:
 # Build RTL simulation
 # - cd ../emulator; make run CONFIG=BOOMConfig

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
 - zip -r $TRAVIS_BUILD_DIR/out/riscv-tools-$BRANCH_N.zip $RISCV
