sudo: required

language: scala
scala: 2.10.6

services:
  - docker
addons:
  artifacts: true
  apt:
   packages:
    # Dependencies from tutorial
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libncurses5-dev
    - libusb-1.0-0
    - libboost-dev
    - zip

# Environment
env:
 global:
 #temp: force parameters for lowRISC
  - $BRANCH_N=ethernet-v0.5
  - $REPO=https://github.com/lowRISC/lowrisc-chip.git
  
  - RISCV=$TRAVIS_BUILD_DIR/riscv-tools-$BRANCH_N
  - PATH=$RISCV/bin:$PATH

before_install:
 - mkdir -p $TRAVIS_BUILD_DIR/out
 - git submodule update --init --recursive
 - wget -q "https://s3.amazonaws.com/ci-build-test/ahmedkhalaf/CI-Test2/41/41.1/out/riscv-tools-ethernet-v0.5.zip"

# Execute the build
install:
# steps not needed because of incremental build are commented
 - git clone -b $BRANCH_N $REPO $BRANCH_N
 - cd $BRANCH_N
 - git submodule update --init --recursive
 - bash set_env.sh
 - unzip ../riscv-tools-*.zip -d $RISCV > $TRAVIS_BUILD_DIR/out/unzip_riscv-tools.txt
 - cd riscv-tools
 - cd riscv-gnu-toolchain
 - ./configure --prefix=$RISCV --enable-multilib
 - make linux -j
 - cd ../..

#script:
 # Build RTL simulation
 # - cd ../emulator; make run CONFIG=BOOMConfig

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
 - zip -r ../out/lowRISC-make-linux-$BRANCH_N.zip ./*  > $TRAVIS_BUILD_DIR/out/zip_lowRISC-make-linux-$BRANCH_N.txt
