sudo: required

language: scala

services:
  - docker
addons:
  artifacts: true
  apt:
   packages:
    # Dependencies from tutorial
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libncurses5-dev
    - libusb-1.0-0
    - libboost-dev

# Environment
env:
 global:
  - VERILATOR_ROOT=$HOME/tools/verilator
  - PATH=$VERILATOR_ROOT/bin:$PATH
  - JOBS=4
  - REPO=https://github.com/lowRISC/lowrisc-chip.git 
  - BRANCH_N=ethernet-v0.5

before_install:
 - git submodule update --init --recursive

# Execute the build
install:
 - git clone -b $BRANCH_N $REPO --recursive $BRANCH_N
 - cd $BRANCH_N
 - source set_env.sh
 - cd riscv-tools/
 - bash build.sh
 - cd riscv-gnu-toolchain
 - cd build/
 - ../configure --prefix=$RISCV
 - make linux -j 4

script:
 # Build RTL simulation
 - cd $TOP/vsim
 - make sim
 # Build RTL simulation with vcd
 - cd $TOP/vsim
 - make sim-debug
 # Run asm tests
 # Add . to PATH so that make finds it (will be changed)
 - export PATH=.:$PATH
 - make run-asm-tests

#before_install:
#- docker pull carlad/sinatra
#- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#- bundle exec rake test
